function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function xml(body,status=200){return new Response(body,{status,headers:{"content-type":"text/xml; charset=utf-8"}});}
function clean(v="",max=5000){return String(v??"").trim().slice(0,max);}
function now(){return Date.now();}
function id(prefix){return `${prefix}_${crypto.randomUUID()}`;}
function basicAuth(sid,token){return `Basic ${btoa(`${sid}:${token}`)}`;}
function phoneKey(v=""){const d=String(v||"").replace(/\D/g,"");return d.length>=10?d.slice(-10):d;}
async function sha256(v){return new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(v))));}
async function sameSecret(a,b){const [x,y]=await Promise.all([sha256(a),sha256(b)]);let d=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)d|=(x[i]??0)^(y[i]??0);return d===0;}
async function authorized(request,env){const expected=clean(env.INTERNAL_CALL_SECRET,1000),given=request.headers.get("x-internal-call-secret")||"";return Boolean(expected&&given&&await sameSecret(expected,given));}
async function parseBody(request){const type=request.headers.get("content-type")||"";if(type.includes("application/json"))return request.json().catch(()=>({}));if(type.includes("x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(await request.text()));return {};}
async function validateTwilio(request,env,body){const token=clean(env.TWILIO_AUTH_TOKEN,400),provided=request.headers.get("x-twilio-signature")||"";if(!token||!provided)return false;const u=new URL(request.url);let signed=`${u.protocol}//${u.host}${u.pathname}${u.search}`;for(const key of Object.keys(body||{}).sort())signed+=`${key}${body[key]??""}`;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(token),{name:"HMAC",hash:"SHA-1"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(signed)));let binary="";for(const b of sig)binary+=String.fromCharCode(b);return btoa(binary)===provided;}

async function settings(env){return await env.DB.prepare(`SELECT * FROM communication_settings WHERE id='default'`).first()||{sms_from_number:""};}
async function listNumbers(env){const sid=clean(env.TWILIO_ACCOUNT_SID,120),token=clean(env.TWILIO_AUTH_TOKEN,400);if(!sid||!token)throw new Error("Twilio credentials are not configured");const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/IncomingPhoneNumbers.json?PageSize=100`,{headers:{Authorization:basicAuth(sid,token)}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`Twilio number lookup failed (${r.status})`);const target=`${clean(env.PUBLIC_BASE_URL,1000).replace(/\/$/,"")}/twilio/sms`;return (data.incoming_phone_numbers||[]).filter(n=>n.capabilities?.sms!==false).map(n=>({sid:String(n.sid||""),phoneNumber:String(n.phone_number||""),friendlyName:String(n.friendly_name||""),smsUrl:String(n.sms_url||""),voiceUrl:String(n.voice_url||""),routedToKenji:String(n.sms_url||"")===target,capabilities:n.capabilities||{}}));}
async function routeNumber(env,numberSid,input={}){if(input.confirm!==true)throw new Error("Explicit confirmation is required before changing SMS routing");if(!/^PN[0-9a-fA-F]{32}$/.test(numberSid))throw new Error("Invalid Twilio number SID");const sid=clean(env.TWILIO_ACCOUNT_SID,120),token=clean(env.TWILIO_AUTH_TOKEN,400);const numbers=await listNumbers(env),current=numbers.find(n=>n.sid===numberSid);if(!current)throw new Error("Twilio number not found");const target=`${clean(env.PUBLIC_BASE_URL,1000).replace(/\/$/,"")}/twilio/sms`;const params=new URLSearchParams({SmsUrl:target,SmsMethod:"POST"});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/IncomingPhoneNumbers/${encodeURIComponent(numberSid)}.json`,{method:"POST",headers:{Authorization:basicAuth(sid,token),"content-type":"application/x-www-form-urlencoded"},body:params});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.message||`Twilio SMS route update failed (${r.status})`);return {ok:true,number:{sid:numberSid,phoneNumber:current.phoneNumber,previousSmsUrl:current.smsUrl,smsUrl:target,routedToKenji:true}};}

async function sendMessage(env,messageId){const row=await env.DB.prepare(`SELECT m.*,l.phone,l.dnc,l.contactable,COALESCE(c.sms_opt_in,0) sms_opt_in,s.sms_from_number FROM communication_messages m JOIN leads l ON l.id=m.lead_id LEFT JOIN lead_channel_consent c ON c.lead_id=l.id JOIN communication_settings s ON s.id='default' WHERE m.id=?`).bind(messageId).first();if(!row)throw new Error("SMS message not found");if(row.status==="sent"||row.status==="delivered")return {ok:true,idempotent:true};if(!row.phone)throw new Error("Lead has no phone number");if(row.dnc||!row.contactable)throw new Error("Lead is not contactable by phone");if(!row.sms_opt_in)throw new Error("Lead has not opted in to SMS");const from=clean(row.sms_from_number,60);if(!from)throw new Error("Choose an SMS sender number in Nurture settings before sending");const sid=clean(env.TWILIO_ACCOUNT_SID,120),token=clean(env.TWILIO_AUTH_TOKEN,400);if(!sid||!token)throw new Error("Twilio credentials are not configured");const callback=new URL(`${clean(env.PUBLIC_BASE_URL,1000).replace(/\/$/,"")}/twilio/status`);callback.searchParams.set("messageId",messageId);const params=new URLSearchParams({To:row.phone,From:from,Body:clean(row.body,1500),StatusCallback:callback.toString()});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:"POST",headers:{Authorization:basicAuth(sid,token),"content-type":"application/x-www-form-urlencoded"},body:params});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`Twilio SMS send failed (${r.status})`);await env.DB.prepare(`UPDATE communication_messages SET status=?,provider_id=?,from_value=?,to_value=?,updated_at=? WHERE id=?`).bind(clean(data.status||"sent",40),clean(data.sid,160),from,row.phone,now(),messageId).run();try{env.ANALYTICS?.writeDataPoint({blobs:["sms.sent",messageId,row.lead_id],doubles:[Date.now()]});}catch{}return {ok:true,messageId,providerId:data.sid||"",status:data.status||"sent"};}

async function inboundSms(request,env){const body=await parseBody(request);if(!(await validateTwilio(request,env,body)))return xml("<Response></Response>",403);const from=clean(body.From,60),text=clean(body.Body,3000),providerId=clean(body.MessageSid,160),key=phoneKey(from);let lead=null;if(from)lead=await env.DB.prepare(`SELECT * FROM leads WHERE phone=? ORDER BY updated_at DESC LIMIT 1`).bind(from).first();if(!lead&&key)lead=await env.DB.prepare(`SELECT * FROM leads WHERE phone LIKE ? ORDER BY updated_at DESC LIMIT 1`).bind(`%${key}`).first();if(!lead)return xml("<Response></Response>");const t=now(),messageId=id("msg");await env.DB.prepare(`INSERT INTO communication_messages(id,lead_id,channel,direction,status,provider_id,from_value,to_value,body,created_at,updated_at) VALUES(?,?,'sms','inbound','received',?,?,?,?,?,?)`).bind(messageId,lead.id,providerId,from,clean(body.To,60),text,t,t).run();if(/^(stop|stopall|unsubscribe|cancel|end|quit)$/i.test(text.trim())){await env.DB.prepare(`INSERT INTO lead_channel_consent(lead_id,sms_opt_in,email_opt_in,sms_opt_out_at,consent_source,consent_note,updated_at) VALUES(?,0,0,?,'sms-keyword','Twilio inbound opt-out',?) ON CONFLICT(lead_id) DO UPDATE SET sms_opt_in=0,sms_opt_out_at=excluded.sms_opt_out_at,consent_source=excluded.consent_source,consent_note=excluded.consent_note,updated_at=excluded.updated_at`).bind(lead.id,t,t).run();}
  return xml("<Response></Response>");}
async function statusWebhook(request,env,url){const body=await parseBody(request);if(!(await validateTwilio(request,env,body)))return json({ok:false},403);const messageId=clean(url.searchParams.get("messageId"),180),status=clean(body.MessageStatus||body.SmsStatus,40),providerId=clean(body.MessageSid,160),error=clean(body.ErrorMessage||body.ErrorCode,1000);if(messageId)await env.DB.prepare(`UPDATE communication_messages SET status=?,provider_id=CASE WHEN provider_id='' THEN ? ELSE provider_id END,error=?,updated_at=? WHERE id=?`).bind(status||"unknown",providerId,error,now(),messageId).run();return json({ok:true});}

async function internalApi(request,env,url){if(!(await authorized(request,env)))return json({ok:false,error:"Unauthorized"},401);try{if(url.pathname==="/internal/pass6/status"&&request.method==="GET"){const s=await settings(env),numbers=await listNumbers(env).catch(()=>[]);return json({ok:true,service:"kenji-sms-worker",twilio:Boolean(env.TWILIO_ACCOUNT_SID&&env.TWILIO_AUTH_TOKEN),configuredSender:s.sms_from_number||"",numbers:numbers.length,routedNumbers:numbers.filter(n=>n.routedToKenji).length,webhook:`${clean(env.PUBLIC_BASE_URL,1000).replace(/\/$/,"")}/twilio/sms`});}if(url.pathname==="/internal/pass6/numbers"&&request.method==="GET")return json({ok:true,numbers:await listNumbers(env)});const route=url.pathname.match(/^\/internal\/pass6\/numbers\/(PN[0-9a-fA-F]{32})\/route$/);if(route&&request.method==="POST")return json(await routeNumber(env,route[1],await request.json().catch(()=>({}))));return json({ok:false,error:"SMS route not found"},404);}catch(error){return json({ok:false,error:error?.message||String(error)},400);}}

export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return json({ok:true,service:"kenji-sms-worker",twilio:Boolean(env.TWILIO_ACCOUNT_SID&&env.TWILIO_AUTH_TOKEN)});if(url.pathname==="/twilio/sms"&&request.method==="POST")return inboundSms(request,env);if(url.pathname==="/twilio/status"&&request.method==="POST")return statusWebhook(request,env,url);if(url.pathname.startsWith("/internal/pass6/"))return internalApi(request,env,url);return json({ok:false,error:"Not found"},404);},async queue(batch,env){for(const message of batch.messages){const messageId=clean(message.body?.messageId,180);if(!messageId){message.ack();continue;}try{await sendMessage(env,messageId);message.ack();}catch(error){console.error("Kenji SMS job failed",messageId,error?.message||error);await env.DB.prepare(`UPDATE communication_messages SET status='failed',error=?,updated_at=? WHERE id=?`).bind(clean(error?.message||error,2000),now(),messageId).run().catch(()=>{});if(/opted in|not contactable|sender number|no phone/i.test(String(error?.message||error)))message.ack();else message.retry();}}}};
