const LANES=new Set(['voice','sms','email','video']);
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
function clean(v='',max=4000){return String(v??'').trim().slice(0,max);}
function now(){return Date.now();}
function id(prefix){return `${prefix}_${crypto.randomUUID()}`;}
function clampInt(v,min,max,fallback){const n=Math.round(Number(v));return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;}
async function digest(v){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))));}
async function sameSecret(a,b){const [x,y]=await Promise.all([digest(a),digest(b)]);let d=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)d|=(x[i]??0)^(y[i]??0);return d===0;}
async function authorized(request,env){const expected=clean(env.INTERNAL_CALL_SECRET,1000),given=request.headers.get('x-internal-call-secret')||'';return Boolean(expected&&given&&await sameSecret(expected,given));}
async function lane(env,name){return env.DB.prepare(`SELECT * FROM orchestration_lanes WHERE lane=?`).bind(name).first();}
function laneOut(r){return r?{lane:r.lane,mode:r.mode,enabled:Boolean(r.enabled),circuitOpen:Boolean(r.circuit_open),perMinute:Number(r.per_minute||0),burst:Number(r.burst||0),shardCount:Number(r.shard_count||1),dailyCapacity:Number(r.per_minute||0)*1440,note:r.note||'',updatedAt:r.updated_at}:null;}
async function lanes(env){const rs=await env.DB.prepare(`SELECT * FROM orchestration_lanes ORDER BY CASE lane WHEN 'voice' THEN 1 WHEN 'sms' THEN 2 WHEN 'email' THEN 3 ELSE 4 END`).all();return rs.results.map(laneOut);}
async function event(env,laneName,type,data={},actor='system'){await env.DB.prepare(`INSERT INTO orchestration_events(id,lane,type,actor,data_json,created_at) VALUES(?,?,?,?,?,?)`).bind(id('orch'),laneName||'',type,actor,JSON.stringify(data||{}),now()).run();}
function hashKey(value=''){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
async function permit(env,laneName,shardKey='default',count=1){const cfg=await lane(env,laneName);if(!cfg)return {allowed:false,reason:'unknown-lane',retryAfterSeconds:60};if(!cfg.enabled)return {allowed:false,reason:'lane-disabled',retryAfterSeconds:300};if(cfg.circuit_open)return {allowed:false,reason:'circuit-open',retryAfterSeconds:300};if(cfg.mode!=='queue')return {allowed:true,reason:'advisory-lane',retryAfterSeconds:0};const shards=Math.max(1,Number(cfg.shard_count||1)),shard=hashKey(shardKey)%shards,perShard=Math.max(1,Math.ceil(Number(cfg.per_minute||1)/shards)),burst=Math.max(0,Math.ceil(Number(cfg.burst||0)/shards));const objectId=env.GOVERNORS.idFromName(`${laneName}:${shard}`),stub=env.GOVERNORS.get(objectId);const response=await stub.fetch('https://governor.internal/permit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limit:perShard,burst,count:Math.max(1,Number(count)||1)})});const result=await response.json();return {...result,lane:laneName,shard,shards,perShard};}
function targetQueue(env,laneName){if(laneName==='voice')return env.VOICE_OUT;if(laneName==='sms')return env.SMS_OUT;if(laneName==='email')return env.EMAIL_OUT;return null;}
function laneFromQueue(name=''){if(name.includes('voice'))return 'voice';if(name.includes('sms'))return 'sms';if(name.includes('email'))return 'email';return '';}
async function handleQueue(batch,env){const laneName=laneFromQueue(batch.queue||'');const out=targetQueue(env,laneName);if(!laneName||!out){for(const msg of batch.messages)msg.retry({delaySeconds:60});return;}for(const msg of batch.messages){const body=msg.body||{},shardKey=body.sourceAccount||body.campaignId||body.sequenceId||body.leadId||body.messageId||'default';try{const p=await permit(env,laneName,shardKey,1);if(!p.allowed){try{env.ANALYTICS?.writeDataPoint({blobs:['denied',laneName,p.reason||''],doubles:[Date.now(),p.retryAfterSeconds||60]});}catch{}msg.retry({delaySeconds:Math.max(5,Math.min(300,Number(p.retryAfterSeconds||60)))});continue;}await out.send(body);try{env.ANALYTICS?.writeDataPoint({blobs:['forwarded',laneName,String(p.shard)],doubles:[Date.now()]});}catch{}msg.ack();}catch(error){console.error('Kenji orchestrator forwarding failed',laneName,error);msg.retry({delaySeconds:30});}}}
async function updateLane(env,name,input={}){if(!LANES.has(name))throw new Error('Unknown lane');const current=await lane(env,name);if(!current)throw new Error('Lane is not configured');const perMinute=clampInt(input.perMinute??current.per_minute,1,100000,current.per_minute),burst=clampInt(input.burst??current.burst,0,50000,current.burst),shardCount=clampInt(input.shardCount??current.shard_count,1,128,current.shard_count),enabled=input.enabled===undefined?Boolean(current.enabled):Boolean(input.enabled),circuitOpen=input.circuitOpen===undefined?Boolean(current.circuit_open):Boolean(input.circuitOpen),note=clean(input.note??current.note,1000),t=now();await env.DB.prepare(`UPDATE orchestration_lanes SET enabled=?,circuit_open=?,per_minute=?,burst=?,shard_count=?,note=?,updated_at=? WHERE lane=?`).bind(enabled?1:0,circuitOpen?1:0,perMinute,burst,shardCount,note,t,name).run();await event(env,name,'lane.updated',{enabled,circuitOpen,perMinute,burst,shardCount},'owner');return laneOut(await lane(env,name));}
async function dryRun(env,input={}){const name=clean(input.lane,40);if(!LANES.has(name))throw new Error('Choose voice, sms, email or video');const cfg=await lane(env,name);if(!cfg)throw new Error('Lane not configured');const jobs=clampInt(input.jobs,1,1000000000,1000000),perMinute=Math.max(1,Number(cfg.per_minute||1)),minutes=jobs/perMinute,daily=perMinute*1440,requiredForDay=Math.ceil(jobs/1440),result={lane:name,jobs,configuredPerMinute:perMinute,shardCount:Number(cfg.shard_count||1),estimatedMinutes:Number(minutes.toFixed(2)),estimatedHours:Number((minutes/60).toFixed(2)),estimatedDailyCapacity:daily,requiredPerMinuteFor24h:requiredForDay,meets24HourTarget:daily>=jobs,providerCapacityNotGuaranteed:true};await env.DB.prepare(`INSERT INTO orchestration_load_tests(id,lane,requested_jobs,per_minute,shard_count,estimated_minutes,estimated_daily_capacity,created_by,created_at) VALUES(?,?,?,?,?,?,?,'owner',?)`).bind(id('load'),name,jobs,perMinute,Number(cfg.shard_count||1),minutes,daily,now()).run();return result;}
async function api(request,env,url){if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized'},401);try{if(url.pathname==='/internal/pass7/status'&&request.method==='GET')return json({ok:true,lanes:await lanes(env),ingress:{voice:'kenji-orch-voice-ingress',sms:'kenji-orch-sms-ingress',email:'kenji-orch-email-ingress'},execution:{voice:'kenji-call-jobs',sms:'kenji-sms-jobs',email:'kenji-email-jobs'},capturedAt:now()});const m=url.pathname.match(/^\/internal\/pass7\/lanes\/(voice|sms|email|video)$/);if(m&&request.method==='PUT')return json({ok:true,lane:await updateLane(env,m[1],await request.json().catch(()=>({})))});if(url.pathname==='/internal/pass7/pause-all'&&request.method==='POST'){await env.DB.prepare(`UPDATE orchestration_lanes SET circuit_open=1,updated_at=? WHERE mode='queue'`).bind(now()).run();await event(env,'','all.circuit-open',{},'owner');return json({ok:true,lanes:await lanes(env)});}if(url.pathname==='/internal/pass7/resume-all'&&request.method==='POST'){await env.DB.prepare(`UPDATE orchestration_lanes SET circuit_open=0,updated_at=? WHERE mode='queue'`).bind(now()).run();await event(env,'','all.circuit-closed',{},'owner');return json({ok:true,lanes:await lanes(env)});}if(url.pathname==='/internal/pass7/dry-run'&&request.method==='POST')return json({ok:true,result:await dryRun(env,await request.json().catch(()=>({})))});if(url.pathname==='/internal/pass7/permit'&&request.method==='POST'){const input=await request.json().catch(()=>({}));return json({ok:true,...await permit(env,clean(input.lane,40),clean(input.shardKey,300),Number(input.count||1))});}return json({ok:false,error:'Pass 7 route not found'},404);}catch(error){console.error('Kenji orchestrator API failed',error);return json({ok:false,error:error?.message||String(error)},400);}}

export class LaneGovernor{constructor(state){this.state=state;}async fetch(request){const input=await request.json().catch(()=>({})),limit=Math.max(1,Number(input.limit||1)),burst=Math.max(0,Number(input.burst||0)),count=Math.max(1,Number(input.count||1)),minute=Math.floor(Date.now()/60000);let s=await this.state.storage.get(['minute','used']);let used=Number(s.get('used')||0);if(Number(s.get('minute'))!==minute)used=0;const cap=limit+burst,allowed=used+count<=cap;if(allowed){used+=count;await this.state.storage.put({minute,used});}const sec=60-Math.floor((Date.now()%60000)/1000);return json({allowed,used,limit,burst,capacity:cap,retryAfterSeconds:allowed?0:Math.max(1,sec)});}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/internal/pass7/'))return api(request,env,url);if(url.pathname==='/health')return json({ok:true,service:'kenji-orchestrator-worker'});return json({ok:false,error:'Not found'},404);},async queue(batch,env){await handleQueue(batch,env);}};
