import app from "./pass2.js";

const ACTION_TTL=15*60*1000;
const ACTIONS=new Set(["call_lead","schedule_callback","update_stage","create_appointment","pull_highlevel"]);
const STAGES=new Set(["New","Attempted","Contacted","Qualified","Booked","Won","Nurture","Lost"]);

function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function clean(v="",max=6000){return String(v??"").trim().slice(0,max);}
function now(){return Date.now();}
function id(prefix){return `${prefix}_${crypto.randomUUID()}`;}
function parseJsonText(value=""){const text=String(value||"").trim();try{return JSON.parse(text);}catch{}const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i);if(fenced)try{return JSON.parse(fenced[1]);}catch{}const match=text.match(/\{[\s\S]*\}/);if(match)try{return JSON.parse(match[0]);}catch{}return null;}

async function authUser(request,env){const cookie=request.headers.get("cookie")||"";const response=await app.fetch(new Request("https://kenji.internal/api/auth/status",{headers:{cookie}}),env,{});const data=await response.json().catch(()=>({}));return response.ok&&data.authenticated?data.user:null;}
async function service(binding,secret,path,{method="GET",body}={}){if(!binding||typeof binding.fetch!=="function")throw new Error("Required service binding is unavailable");const headers={"x-internal-call-secret":String(secret||"")};if(body!==undefined)headers["content-type"]="application/json";const response=await binding.fetch(new Request(`https://service.internal${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}));const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={raw:text};}if(!response.ok||data?.ok===false)throw new Error(data?.error||`Service failed (${response.status})`);return data;}
async function data(env,path,opts){return service(env.DATA,env.INTERNAL_CALL_SECRET,path,opts);}
async function highlevel(env,path,opts){return service(env.HIGHLEVEL,env.INTERNAL_CALL_SECRET,path,opts);}

async function actionContext(env){const [leads,agency]=await Promise.all([env.DB.prepare(`SELECT l.id,l.first_name,l.last_name,l.company,l.phone,l.stage,l.score,l.source,l.source_account,l.contactable,l.dnc,hl.location_id,hl.contact_id FROM leads l LEFT JOIN highlevel_links hl ON hl.lead_id=l.id ORDER BY l.score DESC,l.updated_at DESC LIMIT 80`).all(),highlevel(env,"/api/highlevel/pass3/agency-ops").catch(()=>({agency:{locations:[]}}))]);return {leads:leads.results.map(r=>({id:r.id,name:`${r.first_name} ${r.last_name}`.trim(),company:r.company,phone:r.phone,stage:r.stage,score:r.score,source:r.source,sourceAccount:r.source_account,contactable:Boolean(r.contactable),dnc:Boolean(r.dnc),highlevelLocationId:r.location_id||"",highlevelContactId:r.contact_id||""})),locations:agency?.agency?.locations||[]};}
async function runtimePlan(env,instruction,ctx){const base=clean(env.EILA_RUNTIME_URL,1000).replace(/\/$/,""),token=clean(env.EILA_RUNTIME_TOKEN,1000);if(!base||!token)throw new Error("EILA runtime is not configured");const prompt=["SYSTEM: Convert the owner's Kenji call-center instruction into ONE safe structured action preview. Return JSON only, no markdown.",'Supported action types: call_lead, schedule_callback, update_stage, create_appointment, pull_highlevel.','Schema: {"actionType":"...","targetId":"exact leadId or locationId","payload":{},"explanation":"plain English preview"}',"call_lead payload is {}.",'schedule_callback payload is {"dueAt":"ISO-8601","reason":"..."}.','update_stage payload is {"stage":"New|Attempted|Contacted|Qualified|Booked|Won|Nurture|Lost"}.','create_appointment payload is {"startTime":"ISO-8601","durationMinutes":30,"title":"..."}. Use only if the owner explicitly asks to book/create/schedule an appointment.',"pull_highlevel targetId is the exact HighLevel locationId and payload is {}.",'Never invent an ID. If the instruction is ambiguous or unsupported, return {"actionType":"","targetId":"","payload":{},"explanation":"What you need clarified"}.',`CURRENT_UTC: ${new Date().toISOString()}`,`AVAILABLE_CONTEXT: ${JSON.stringify(ctx).slice(0,22000)}`,`OWNER_INSTRUCTION: ${instruction}`].join("\n\n");const response=await fetch(`${base}/chat`,{method:"POST",headers:{"content-type":"application/json","x-runtime-token":token},body:JSON.stringify({text:prompt,tenantId:"kenji",sessionId:`action_plan_${crypto.randomUUID()}`,interest:"operator action planning"})});const out=await response.json().catch(()=>({}));if(!response.ok)throw new Error(out.detail||out.error||`Action planner failed (${response.status})`);const parsed=parseJsonText(out.response||out.text);if(!parsed)throw new Error("Isla action planner returned invalid JSON");return parsed;}

async function validatePlan(env,plan,ctx){const actionType=clean(plan.actionType,80),targetId=clean(plan.targetId,180),payload=plan.payload&&typeof plan.payload==="object"?plan.payload:{},explanation=clean(plan.explanation,1000);if(!ACTIONS.has(actionType))throw new Error(explanation||"Isla needs a more specific instruction before proposing an action");if(!targetId)throw new Error("Isla could not resolve a target");if(actionType==="pull_highlevel"){const loc=ctx.locations.find(x=>x.locationId===targetId);if(!loc)throw new Error("Isla referenced a HighLevel location that is not in the current agency view");return {actionType,targetId,payload:{},explanation:explanation||`Pull fresh HighLevel data for ${loc.name||targetId}.`};}const lead=ctx.leads.find(x=>x.id===targetId);if(!lead)throw new Error("Isla referenced a lead that is not in the current pipeline");if(actionType==="call_lead"&&(lead.dnc||!lead.contactable||!lead.phone))throw new Error("That lead cannot be called with the current contactability state");if(actionType==="update_stage"){const next=clean(payload.stage,40);if(!STAGES.has(next))throw new Error("Isla proposed an invalid pipeline stage");payload.stage=next;}if(actionType==="schedule_callback"){const due=Date.parse(String(payload.dueAt||""));if(!Number.isFinite(due)||due<=now())throw new Error("Callback time must be in the future");payload.dueAt=new Date(due).toISOString();payload.reason=clean(payload.reason||"Isla scheduled follow-up",500);}if(actionType==="create_appointment"){if(!lead.highlevelLocationId||!lead.highlevelContactId)throw new Error("That lead is not linked to HighLevel yet, so Isla cannot create a HighLevel appointment for it");const start=Date.parse(String(payload.startTime||""));if(!Number.isFinite(start)||start<=now())throw new Error("Appointment time must be in the future");payload.startTime=new Date(start).toISOString();payload.durationMinutes=Math.max(15,Math.min(240,Number(payload.durationMinutes)||30));payload.title=clean(payload.title||`Follow-up with ${lead.name||"lead"}`,240);}return {actionType,targetId,payload,explanation:explanation||`${actionType.replaceAll("_"," ")} for ${lead.name||targetId}.`};}
async function createAction(env,user,instruction,plan){const actionId=id("action"),t=now();await env.DB.prepare(`INSERT INTO operator_actions(id,owner_user_id,instruction,action_type,target_id,payload_json,explanation,status,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'pending',?,?,?)`).bind(actionId,user.id,clean(instruction,3000),plan.actionType,plan.targetId,JSON.stringify(plan.payload),plan.explanation,t+ACTION_TTL,t,t).run();return {id:actionId,...plan,status:"pending",expiresAt:t+ACTION_TTL};}
async function planAction(request,env,user){const input=await request.json().catch(()=>({})),instruction=clean(input.instruction||input.message,3000);if(!instruction)return json({ok:false,error:"Tell Isla what you want done"},400);const ctx=await actionContext(env),plan=await validatePlan(env,await runtimePlan(env,instruction,ctx),ctx),action=await createAction(env,user,instruction,plan);return json({ok:true,action,requiresConfirmation:true});}
async function executeAction(env,user,actionId){const row=await env.DB.prepare(`SELECT * FROM operator_actions WHERE id=? AND owner_user_id=? LIMIT 1`).bind(actionId,user.id).first();if(!row)throw new Error("Action preview not found");if(row.status==="executed")return {ok:true,idempotent:true,actionId,result:JSON.parse(row.result_json||"{}")};if(row.status!=="pending")throw new Error(`Action is ${row.status}`);if(Number(row.expires_at)<=now()){await env.DB.prepare(`UPDATE operator_actions SET status='expired',updated_at=? WHERE id=?`).bind(now(),actionId).run();throw new Error("Action preview expired. Ask Isla to plan it again.");}const payload=JSON.parse(row.payload_json||"{}");let result={};try{if(row.action_type==="call_lead")result=await data(env,`/api/leads/${encodeURIComponent(row.target_id)}/call`,{method:"POST",body:{}});else if(row.action_type==="schedule_callback")result=await data(env,`/api/leads/${encodeURIComponent(row.target_id)}/callback`,{method:"POST",body:{dueAt:Date.parse(payload.dueAt),reason:payload.reason}});else if(row.action_type==="update_stage")result=await data(env,`/api/leads/${encodeURIComponent(row.target_id)}`,{method:"PUT",body:{stage:payload.stage}});else if(row.action_type==="pull_highlevel")result=await highlevel(env,"/api/highlevel/sync",{method:"POST",body:{locationId:row.target_id}});else if(row.action_type==="create_appointment"){const created=await highlevel(env,"/api/highlevel/pass3/appointments",{method:"POST",body:{leadId:row.target_id,startTime:payload.startTime,durationMinutes:payload.durationMinutes,title:payload.title,createdBy:"isla-overwatch"}});result=await highlevel(env,`/api/highlevel/pass3/appointments/${encodeURIComponent(created.appointment.id)}/confirm`,{method:"POST",body:{}});}else throw new Error("Unsupported action");await env.DB.prepare(`UPDATE operator_actions SET status='executed',result_json=?,updated_at=? WHERE id=?`).bind(JSON.stringify(result),now(),actionId).run();return {ok:true,actionId,result};}catch(error){await env.DB.prepare(`UPDATE operator_actions SET status='failed',error=?,updated_at=? WHERE id=?`).bind(clean(error?.message||error,3000),now(),actionId).run();throw error;}}
async function listActions(env,user){const rs=await env.DB.prepare(`SELECT id,instruction,action_type,target_id,payload_json,explanation,status,result_json,error,expires_at,created_at,updated_at FROM operator_actions WHERE owner_user_id=? ORDER BY created_at DESC LIMIT 30`).bind(user.id).all();return rs.results.map(r=>({...r,payload:JSON.parse(r.payload_json||"{}"),result:JSON.parse(r.result_json||"{}")}));}

export default {async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname.startsWith("/api/pass3/")||url.pathname.startsWith("/api/isla/actions/")){const user=await authUser(request,env);if(!user)return json({ok:false,error:"Authentication required"},401);try{if(url.pathname==="/api/pass3/agency-ops"&&request.method==="GET")return json(await highlevel(env,"/api/highlevel/pass3/agency-ops"));if(url.pathname==="/api/pass3/appointments"&&request.method==="GET")return json(await highlevel(env,"/api/highlevel/pass3/appointments"));const confirm=url.pathname.match(/^\/api\/pass3\/appointments\/([^/]+)\/confirm$/);if(confirm&&request.method==="POST")return json(await highlevel(env,`/api/highlevel/pass3/appointments/${encodeURIComponent(confirm[1])}/confirm`,{method:"POST",body:{}}));if(url.pathname==="/api/isla/actions/plan"&&request.method==="POST")return planAction(request,env,user);if(url.pathname==="/api/isla/actions"&&request.method==="GET")return json({ok:true,actions:await listActions(env,user)});const execute=url.pathname.match(/^\/api\/isla\/actions\/([^/]+)\/execute$/);if(execute&&request.method==="POST")return json(await executeAction(env,user,decodeURIComponent(execute[1])));return json({ok:false,error:"Pass 3 route not found"},404);}catch(error){console.error("Kenji Pass 3 operator route failed",error);return json({ok:false,error:error?.message||String(error)},400);}}const response=await app.fetch(request,env,ctx);const type=response.headers.get("content-type")||"";if(request.method==="GET"&&type.includes("text/html")){const html=await response.text(),injected=html.includes("/pass3-ops.js")?html:html.replace("</body>",'  <script src="/pass3-ops.js"></script>\n</body>');return new Response(injected,{status:response.status,headers:response.headers});}return response;}};
