import app from "./pass7.js";
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function clean(v="",max=5000){return String(v??"").trim().slice(0,max);}
function now(){return Date.now();}
function id(prefix){return `${prefix}_${crypto.randomUUID()}`;}
async function authUser(request,env){const cookie=request.headers.get("cookie")||"";const r=await app.fetch(new Request("https://kenji.internal/api/auth/status",{headers:{cookie}}),env,{});const d=await r.json().catch(()=>({}));return r.ok&&d.authenticated?d.user:null;}
async function service(binding,secret,path,{method="GET",body}={}){if(!binding||typeof binding.fetch!=="function")throw new Error("Required service binding is unavailable");const headers={"x-internal-call-secret":String(secret||"")};if(body!==undefined)headers["content-type"]="application/json";const r=await binding.fetch(new Request(`https://service.internal${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}));const text=await r.text();let d={};try{d=text?JSON.parse(text):{};}catch{d={raw:text};}if(!r.ok||d?.ok===false)throw new Error(d?.error||`Service failed (${r.status})`);return d;}
async function getJob(env,jobId,userId){return env.DB.prepare(`SELECT * FROM video_jobs WHERE id=? AND owner_user_id=? LIMIT 1`).bind(jobId,userId).first();}
async function waitForJob(env,jobId,userId,timeoutMs=25000){const start=now();while(now()-start<timeoutMs){const row=await getJob(env,jobId,userId);if(!row)throw new Error("Video job disappeared from the queue ledger");if(row.status==="ready"){if(row.expires_at&&Number(row.expires_at)<now())throw new Error("Video session token expired before delivery");let data={};try{data=JSON.parse(row.result_json||"{}");}catch{}return {ok:true,...data,videoJobId:jobId,queueStatus:"ready"};}if(row.status==="failed")throw new Error(row.error||"Video worker failed to create the room");await new Promise(r=>setTimeout(r,750));}throw new Error("Video lane is busy. The job is still queued; try Isla Live again in a few seconds.");}
async function queueVideo(env,user){if(!env.VIDEO_INGRESS||typeof env.VIDEO_INGRESS.send!=="function")throw new Error("Video ingress queue is unavailable");let row=await env.DB.prepare(`SELECT * FROM video_jobs WHERE owner_user_id=? AND status IN ('queued','creating') AND created_at>? ORDER BY created_at DESC LIMIT 1`).bind(user.id,now()-120000).first();let jobId=row?.id;if(!jobId){jobId=id("video");const t=now();await env.DB.prepare(`INSERT INTO video_jobs(id,owner_user_id,owner_name,status,attempts,result_json,error,queued_at,created_at,updated_at) VALUES(?,?,?,'queued',0,'{}','',?,?,?)`).bind(jobId,user.id,clean(user.name,160),t,t,t).run();try{await env.VIDEO_INGRESS.send({type:"video.session.create",jobId,ownerUserId:user.id,shardKey:user.id,queuedAt:t});}catch(error){await env.DB.prepare(`UPDATE video_jobs SET status='failed',error=?,completed_at=?,updated_at=? WHERE id=?`).bind(clean(error?.message||error,3000),now(),now(),jobId).run();throw error;}}return waitForJob(env,jobId,user.id);}
async function videoReadiness(env){const worker=await service(env.VIDEO_QUEUE,env.INTERNAL_CALL_SECRET,"/internal/pass8/status").catch(error=>({ok:false,error:error.message}));const lane=await env.DB.prepare(`SELECT lane,mode,enabled,circuit_open,per_minute,burst,shard_count,note,updated_at FROM orchestration_lanes WHERE lane='video'`).first();return {ok:Boolean(worker?.ok&&lane&&lane.mode==="queue"&&lane.enabled&&!lane.circuit_open),queueBacked:true,worker,lane:lane?{lane:lane.lane,mode:lane.mode,enabled:Boolean(lane.enabled),circuitOpen:Boolean(lane.circuit_open),perMinute:Number(lane.per_minute||0),burst:Number(lane.burst||0),shardCount:Number(lane.shard_count||1),note:lane.note||""}:null};}
async function rehearsal(request,env){const cookie=request.headers.get("cookie")||"";const fetchLocal=async path=>{const r=await app.fetch(new Request(`https://kenji.internal${path}`,{headers:{cookie}}),env,{});return r.json().catch(()=>({ok:false,error:`${path} returned ${r.status}`}));};const [demo,nurture,scale,video]=await Promise.all([fetchLocal("/api/pass4/readiness").catch(e=>({ok:false,error:e.message})),fetchLocal("/api/pass6/readiness").catch(e=>({ok:false,error:e.message})),fetchLocal("/api/pass7/status").catch(e=>({ok:false,error:e.message})),videoReadiness(env)]);const checks={data:Boolean(env.DB&&env.DATA),voice:Boolean(demo?.voice?.twilio&&demo?.voice?.deepgram&&demo?.voice?.runtime),sms:Boolean(nurture?.sms?.ok!==false),email:Boolean(nurture?.email?.ok!==false),nurture:Boolean(nurture?.nurture),orchestrator:Boolean(scale?.ok!==false&&Array.isArray(scale?.lanes)),video:Boolean(video?.ok)};return {ok:Object.values(checks).every(Boolean),checks,demo,nurture,scale,video,capturedAt:now(),providerTrafficSent:false};}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/video/session"&&request.method==="POST"){const user=await authUser(request,env);if(!user)return json({ok:false,error:"Authentication required"},401);try{return json(await queueVideo(env,user));}catch(error){console.error("Kenji Pass 8 video queue failed",error);return json({ok:false,error:error?.message||String(error)},503);}}if(url.pathname==="/api/video/readiness"&&request.method==="GET"){const user=await authUser(request,env);if(!user)return json({ok:false,error:"Authentication required"},401);return json(await videoReadiness(env));}const job=url.pathname.match(/^\/api\/pass8\/video\/jobs\/([^/]+)$/);if(job&&request.method==="GET"){const user=await authUser(request,env);if(!user)return json({ok:false,error:"Authentication required"},401);const row=await getJob(env,decodeURIComponent(job[1]),user.id);if(!row)return json({ok:false,error:"Video job not found"},404);return json({ok:true,id:row.id,status:row.status,attempts:row.attempts,error:row.error||"",queuedAt:row.queued_at,startedAt:row.started_at,completedAt:row.completed_at,expiresAt:row.expires_at});}if(url.pathname==="/api/pass8/rehearsal"&&request.method==="GET"){const user=await authUser(request,env);if(!user)return json({ok:false,error:"Authentication required"},401);return json(await rehearsal(request,env));}const response=await app.fetch(request,env,ctx);const type=response.headers.get("content-type")||"";if(request.method==="GET"&&type.includes("text/html")){const html=await response.text(),injected=html.includes("/pass8-rehearsal.js")?html:html.replace("</body>",'  <script src="/pass8-rehearsal.js"></script>\n</body>');return new Response(injected,{status:response.status,headers:response.headers});}return response;}};
