function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function clean(v="",max=10000){return String(v??"").trim().slice(0,max);}
function now(){return Date.now();}
async function sha256(v){return new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(v))));}
async function sameSecret(a,b){const [x,y]=await Promise.all([sha256(a),sha256(b)]);let d=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)d|=(x[i]??0)^(y[i]??0);return d===0;}
async function authorized(request,env){const expected=clean(env.INTERNAL_CALL_SECRET,1000),given=request.headers.get("x-internal-call-secret")||"";return Boolean(expected&&given&&await sameSecret(expected,given));}
async function settings(env){return await env.DB.prepare(`SELECT * FROM communication_settings WHERE id='default'`).first()||{email_from:"",reply_to:""};}

async function sendEmail(env,messageId){const row=await env.DB.prepare(`SELECT m.*,l.email,COALESCE(c.email_opt_in,0) email_opt_in,s.email_from,s.reply_to FROM communication_messages m JOIN leads l ON l.id=m.lead_id LEFT JOIN lead_channel_consent c ON c.lead_id=l.id JOIN communication_settings s ON s.id='default' WHERE m.id=?`).bind(messageId).first();if(!row)throw new Error("Email message not found");if(row.status==="sent"||row.status==="delivered")return {ok:true,idempotent:true};if(!row.email)throw new Error("Lead has no email address");if(!row.email_opt_in)throw new Error("Lead has not opted in to email");const from=clean(row.email_from,320);if(!from)throw new Error("Configure an email sender in Nurture settings before sending");const token=clean(env.RESEND_API_KEY,2000);if(!token)throw new Error("Resend API key is not configured");const payload={from,to:[row.email],subject:clean(row.subject||"Follow-up",300),text:clean(row.body,9000)};const replyTo=clean(row.reply_to,320);if(replyTo)payload.reply_to=replyTo;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`Resend send failed (${response.status})`);await env.DB.prepare(`UPDATE communication_messages SET status='sent',provider_id=?,from_value=?,to_value=?,updated_at=? WHERE id=?`).bind(clean(data.id,180),from,row.email,now(),messageId).run();try{env.ANALYTICS?.writeDataPoint({blobs:["email.sent",messageId,row.lead_id],doubles:[Date.now()]});}catch{}return {ok:true,messageId,providerId:data.id||""};}

async function internalApi(request,env,url){if(!(await authorized(request,env)))return json({ok:false,error:"Unauthorized"},401);try{if(url.pathname==="/internal/pass6/status"&&request.method==="GET"){const s=await settings(env);return json({ok:true,service:"kenji-email-worker",resend:Boolean(env.RESEND_API_KEY),configuredSender:s.email_from||"",replyTo:s.reply_to||""});}return json({ok:false,error:"Email route not found"},404);}catch(error){return json({ok:false,error:error?.message||String(error)},400);}}

export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return json({ok:true,service:"kenji-email-worker",resend:Boolean(env.RESEND_API_KEY)});if(url.pathname.startsWith("/internal/pass6/"))return internalApi(request,env,url);return json({ok:false,error:"Not found"},404);},async queue(batch,env){for(const message of batch.messages){const messageId=clean(message.body?.messageId,180);if(!messageId){message.ack();continue;}try{await sendEmail(env,messageId);message.ack();}catch(error){console.error("Kenji email job failed",messageId,error?.message||error);await env.DB.prepare(`UPDATE communication_messages SET status='failed',error=?,updated_at=? WHERE id=?`).bind(clean(error?.message||error,2000),now(),messageId).run().catch(()=>{});if(/opted in|sender|no email/i.test(String(error?.message||error)))message.ack();else message.retry();}}}};
